[project]
name = "cronbach-webapp"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pygsheets>=2.0.6",
    "pymongo>=4.13.0",
    "pyyaml>=6.0.2",
    "redis>=6.2.0",
    "werkzeug>=3.1.3",
]
